apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
 name: auto-instrumentation
spec:
 exporter:
   endpoint: http://otel-collector-collector.default.svc:4318
 propagators:
   - tracecontext
   - baggage
   - b3
 sampler:
   type: parentbased_traceidratio
   argument: "1"
 java:
   image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
 nodejs:
   image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
 python:
   image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
 go:
   image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-go:latest
